Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: us-west-2c
      ImageId: ami-094125af156557ca2 # Mani , Change this AMI ID accordingly   
      InstanceType: t2.micro  # Change the instance type as required
      KeyName: harish-neworegon # Specify your key name here
      SecurityGroupIds:
      - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 32
            DeleteOnTermination: true
            VolumeType: "gp3"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum update -y
            sudo yum upgrade -y
            sudo amazon-linux-extras install epel -y
            sudo yum install -y ansible
            sudo yum install -y httpd.x86_64
            sudo systemctl start httpd.service
            sudo systemctl enable httpd.service
            echo Hi Mani Prashanth > /var/www/html/index.html
  InstanceSecurityGroup:
   # As this is a sample template i opened HTTP and SSH port You can change the port's as required.
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        Description: ssh
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
            